package story

// v4 progressive outline drill-down: book → arc (卷) → act (幕) → chapter (章).
// Each level is generated by its own small AI call and gated by a user
// confirmation before the next level unlocks. The constraint strength
// increases level by level:
//
//	book overview (整书概览, loose)  → arc skeleton + master logic
//	arc outline   (卷纲, medium)      → volume storyline + act split
//	act outline   (幕纲, strong)      → act narrative outline
//	chapter outline (章纲, very strong) → per-chapter outlines (one act per call)
//	prose         (正文)              → existing chapter writing flow
//
// Legacy v3 projects (BookOverview empty) keep the old per-arc chapter
// generation path unchanged; the act layer simply never appears for them.

import (
	"context"
	"encoding/json"
	"fmt"
	"showmethestory/internal/config"
	"showmethestory/internal/i18n"
	"showmethestory/internal/llm"
	"showmethestory/internal/sse"
	"strings"
)

// buildPreviousActContext assembles the "previously" block for act-level and
// chapter-level outline generation inside one arc: summaries of earlier arcs,
// outlines of earlier acts in the same arc, plus the tail chapters right
// before the act start for a tight handoff.
func buildPreviousActContext(state *Progress, arcIdx, actIdx int, lang string) string {
	en := i18n.NormalizeLanguage(lang) == i18n.LangEN
	var sb strings.Builder

	arc := &state.Arcs[arcIdx]
	act := &arc.Acts[actIdx]

	for i := 0; i < arcIdx; i++ {
		prev := &state.Arcs[i]
		if prev.Summary == "" {
			continue
		}
		if en {
			sb.WriteString(fmt.Sprintf("[Arc %d \"%s\" (ch.%d-%d) summary]\n%s\n\n", i+1, prev.Title, prev.StartCh, prev.EndCh, prev.Summary))
		} else {
			sb.WriteString(fmt.Sprintf("【第%d卷《%s》（第%d~%d章）卷摘要】\n%s\n\n", i+1, prev.Title, prev.StartCh, prev.EndCh, prev.Summary))
		}
	}

	for i := 0; i < actIdx; i++ {
		prev := &arc.Acts[i]
		if prev.Outline == "" {
			if prev.Summary != "" {
				if en {
					sb.WriteString(fmt.Sprintf("[Act %d \"%s\" summary] %s\n", i+1, prev.Title, prev.Summary))
				} else {
					sb.WriteString(fmt.Sprintf("[第%d幕《%s》幕摘要] %s\n", i+1, prev.Title, prev.Summary))
				}
			}
			continue
		}
		if en {
			sb.WriteString(fmt.Sprintf("[Act %d \"%s\" (ch.%d-%d) outline]\n%s\n\n", i+1, prev.Title, prev.StartCh, prev.EndCh, prev.Outline))
		} else {
			sb.WriteString(fmt.Sprintf("【第%d幕《%s》（第%d~%d章）幕纲】\n%s\n\n", i+1, prev.Title, prev.StartCh, prev.EndCh, prev.Outline))
		}
	}

	// Tail chapters of the previous act: prefer summaries, fall back to outlines.
	const tailWindow = 5
	var tail []string
	for i := range state.Chapters {
		ch := state.Chapters[i]
		if ch.Num >= act.StartCh || ch.Num < act.StartCh-tailWindow {
			continue
		}
		if ch.Summary != "" {
			if en {
				tail = append(tail, fmt.Sprintf("[Chapter %d summary] %s", ch.Num, ch.Summary))
			} else {
				tail = append(tail, fmt.Sprintf("[第%d章摘要] %s", ch.Num, ch.Summary))
			}
		} else if strings.TrimSpace(ch.Outline) != "" {
			tail = append(tail, strings.TrimRight(formatChapterLine(ch.Num, ch.Title, ch.Outline, lang), "\n"))
		}
	}
	if len(tail) > 0 {
		sb.WriteString(strings.Join(tail, "\n"))
		sb.WriteString("\n")
	}

	if sb.Len() == 0 {
		if en {
			return "This is the opening of the story; no prior context."
		}
		return "当前为故事开端，无历史前情。"
	}
	return sb.String()
}

// buildFutureActsBlock lists the later acts of the same arc (and later arcs)
// so the current act does not pre-consume their key events.
func buildFutureActsBlock(state *Progress, arcIdx, actIdx int, lang string) string {
	en := i18n.NormalizeLanguage(lang) == i18n.LangEN
	var sb strings.Builder
	arc := &state.Arcs[arcIdx]
	for i := actIdx + 1; i < len(arc.Acts); i++ {
		act := arc.Acts[i]
		if en {
			sb.WriteString(fmt.Sprintf("Act %d \"%s\" (ch.%d-%d): %s\n", i+1, act.Title, act.StartCh, act.EndCh, act.Goal))
		} else {
			sb.WriteString(fmt.Sprintf("第%d幕《%s》（第%d~%d章）：%s\n", i+1, act.Title, act.StartCh, act.EndCh, act.Goal))
		}
	}
	// Later arcs still constrain the act's chapter outlines (no early spoilers).
	for i := arcIdx + 1; i < len(state.Arcs); i++ {
		arc := state.Arcs[i]
		if en {
			sb.WriteString(fmt.Sprintf("Arc %d \"%s\" (ch.%d-%d): %s\n", i+1, arc.Title, arc.StartCh, arc.EndCh, arc.Goal))
		} else {
			sb.WriteString(fmt.Sprintf("第%d卷《%s》（第%d~%d章）：%s\n", i+1, arc.Title, arc.StartCh, arc.EndCh, arc.Goal))
		}
	}
	if sb.Len() == 0 {
		if en {
			return "(this is the final act)"
		}
		return "（本幕为最后一幕）"
	}
	return sb.String()
}

// —— 整书概览 (book overview) ——

type bookOverviewResponse struct {
	Title         string `json:"title"`
	StorySynopsis string `json:"story_synopsis"`
	BookOverview  string `json:"book_overview"`
	Arcs          []struct {
		Title        string `json:"title"`
		Goal         string `json:"goal"`
		ChapterCount int    `json:"chapter_count"`
	} `json:"arcs"`
}

// GenerateBookOverviewAction generates the book overview (整书概览): the
// book-level master logic plus the volume skeleton. Refuses when accepted or
// in-progress chapters exist; pending chapters are dropped because they belong
// to the old structure.
func GenerateBookOverviewAction(ctx context.Context, apiCfg *config.APIConfig, cfg *config.Config, state *Progress, settings *ProjectSettings, progressPath, cfgPath string, logger *sse.LogBroadcaster) error {
	if err := llm.ValidateConfig(apiCfg); err != nil {
		return err
	}
	for _, ch := range state.Chapters {
		if ch.Status == StatusAccepted || ch.Status == StatusWriting || ch.Status == StatusReview {
			return fmt.Errorf("存在已确认或写作中的章节，无法重新生成整书概览")
		}
	}

	data := mergeOutlinePromptData(map[string]string{
		"CorePrompt":    state.CorePrompt,
		"StoryType":     cfg.Story.Type,
		"ChapterCount":  fmt.Sprintf("%d", cfg.Story.ChapterCount),
		"TargetWords":   fmt.Sprintf("%d", cfg.Story.TargetWordsPerChapter),
		"WritingStyle":  cfg.Story.WritingStyle,
		"WritingPOV":    cfg.Story.WritingPOV,
		"StorySynopsis": cfg.Story.StorySynopsis,
	}, cfg, settings)
	userPrompt := config.RenderPrompt(cfg.Prompts.BookOverview, data)
	userPrompt = appendIfMissingPlaceholder(cfg.Prompts.BookOverview, userPrompt, "{{.CharacterList}}", formatCharacterListForOutline(settings, cfg.Language))
	systemPrompt := i18n.SystemPromptFor(cfg.Language, "outline_editor_json")

	rawResp := llm.CallAPIWithRetryLog(ctx, apiCfg, systemPrompt, userPrompt, logger)
	if rawResp == "" {
		return fmt.Errorf("API 调用失败或被取消")
	}
	var resp bookOverviewResponse
	if err := json.Unmarshal([]byte(cleanJSONResponse(rawResp)), &resp); err != nil {
		return fmt.Errorf("解析整书概览JSON失败: %w\n原始响应: %s", err, Truncate(rawResp, 500))
	}
	if len(resp.Arcs) == 0 {
		return fmt.Errorf("AI 未返回任何卷")
	}

	counts := make([]int, len(resp.Arcs))
	for i, a := range resp.Arcs {
		counts[i] = a.ChapterCount
	}
	ranges := assignRanges(counts, 1, cfg.Story.ChapterCount)

	state.Arcs = make([]Arc, len(resp.Arcs))
	for i, a := range resp.Arcs {
		state.Arcs[i] = Arc{
			ID:      i + 1,
			Title:   a.Title,
			Goal:    a.Goal,
			StartCh: ranges[i].Start,
			EndCh:   ranges[i].End,
		}
	}
	state.BookOverview = strings.TrimSpace(resp.BookOverview)
	state.BookOverviewConfirmed = false
	// Drop pending chapters from the previous structure.
	state.Chapters = nil
	state.CurrentChapterIndex = 0

	if err := applyOutlineMetaWithGuard(cfg, state, OutlineResponse{Title: resp.Title, StorySynopsis: resp.StorySynopsis}, "book_overview", PendingConfigChangesPath(progressPath), cfgPath, logger); err != nil {
		return err
	}
	snapshot := cfg.Story
	state.StoryConfigSnapshot = &snapshot

	if err := SaveProgress(progressPath, state); err != nil {
		return fmt.Errorf("保存进度失败: %w", err)
	}
	logger.SuccessKey("log.book_overview_done", len(state.Arcs), cfg.Story.ChapterCount)
	return nil
}

// ConfirmBookOverviewAction marks the 整书概览 as confirmed, unlocking 卷纲.
func ConfirmBookOverviewAction(state *Progress, progressPath string) error {
	if state.BookOverview == "" && len(state.Arcs) == 0 {
		return fmt.Errorf("尚无整书概览")
	}
	state.BookOverviewConfirmed = true
	return SaveProgress(progressPath, state)
}

// EditBookOverviewAction edits the 整书概览 text before it is confirmed.
func EditBookOverviewAction(state *Progress, progressPath, outline string) error {
	if state.BookOverviewConfirmed {
		return fmt.Errorf("整书概览已确认，不能修改")
	}
	state.BookOverview = strings.TrimSpace(outline)
	return SaveProgress(progressPath, state)
}

// —— 卷纲 (arc outline + act split) ——

type arcPlanResponse struct {
	Outline string `json:"outline"`
	Acts    []struct {
		Title        string `json:"title"`
		Goal         string `json:"goal"`
		ChapterCount int    `json:"chapter_count"`
	} `json:"acts"`
}

// GenerateArcPlanAction generates the arc outline (卷纲): the volume's detailed
// storyline plus the act breakdown. Requires a confirmed book overview. When the
// project has no book overview (legacy v3), callers should use
// GenerateArcOutlineAction instead (per-arc chapter generation).
func GenerateArcPlanAction(ctx context.Context, apiCfg *config.APIConfig, cfg *config.Config, state *Progress, settings *ProjectSettings, arcID int, requirements, progressPath string, logger *sse.LogBroadcaster) error {
	if err := llm.ValidateConfig(apiCfg); err != nil {
		return err
	}
	if !state.BookOverviewConfirmed {
		return fmt.Errorf("请先确认整书概览，再生成卷纲")
	}
	ai := ArcIndexByID(state, arcID)
	if ai < 0 {
		return fmt.Errorf("卷 %d 不存在", arcID)
	}
	arc := &state.Arcs[ai]
	if arc.Confirmed {
		return fmt.Errorf("第 %d 卷卷纲已确认，如需调整请先取消确认或重新生成", ai+1)
	}
	for _, ch := range arcChapters(state, arc) {
		if ch.Status != StatusPending {
			return fmt.Errorf("第 %d 卷范围内存在已确认/写作中的章节，无法重新生成本卷卷纲", ai+1)
		}
	}

	lang := cfg.Language
	count := arc.EndCh - arc.StartCh + 1
	baseData := map[string]string{
		"Title":          preferUserValue(cfg.Story.Title, state.Title),
		"StoryType":      cfg.Story.Type,
		"CorePrompt":     state.CorePrompt,
		"StorySynopsis":  preferUserValue(cfg.Story.StorySynopsis, state.StorySynopsis),
		"WritingStyle":   cfg.Story.WritingStyle,
		"WritingPOV":     cfg.Story.WritingPOV,
		"BookOverview":   state.BookOverview,
		"PreviousContext": buildPreviousArcContext(state, arc.StartCh, lang),
		"ArcIndex":       fmt.Sprintf("%d", ai+1),
		"ArcTitle":       arc.Title,
		"ArcGoal":        arc.Goal,
		"StartNum":       fmt.Sprintf("%d", arc.StartCh),
		"EndNum":         fmt.Sprintf("%d", arc.EndCh),
		"ChapterCount":   fmt.Sprintf("%d", count),
		"FutureArcs":     buildFutureArcsBlock(state, ai, lang),
		"UserRequirements": strings.TrimSpace(requirements),
		"ActsPerArc":     fmt.Sprintf("%d", cfg.Story.ActsPerArc),
		"ChaptersPerAct": fmt.Sprintf("%d", cfg.Story.ChaptersPerAct),
	}
	if baseData["UserRequirements"] == "" {
		if i18n.NormalizeLanguage(lang) == i18n.LangEN {
			baseData["UserRequirements"] = "(none)"
		} else {
			baseData["UserRequirements"] = "（无）"
		}
	}
	data := mergeOutlinePromptData(baseData, cfg, settings)
	userPrompt := config.RenderPrompt(cfg.Prompts.ArcOutline, data)
	userPrompt = appendIfMissingPlaceholder(cfg.Prompts.ArcOutline, userPrompt, "{{.CharacterList}}", formatCharacterListForOutline(settings, cfg.Language))
	systemPrompt := i18n.SystemPromptFor(lang, "outline_editor_json")

	rawResp := llm.CallAPIWithRetryLog(ctx, apiCfg, systemPrompt, userPrompt, logger)
	if rawResp == "" {
		return fmt.Errorf("API 调用失败或被取消")
	}
	var resp arcPlanResponse
	if err := json.Unmarshal([]byte(cleanJSONResponse(rawResp)), &resp); err != nil {
		return fmt.Errorf("解析卷纲JSON失败: %w\n原始响应: %s", err, Truncate(rawResp, 500))
	}
	if len(resp.Acts) == 0 {
		return fmt.Errorf("AI 未返回任何幕")
	}

	counts := make([]int, len(resp.Acts))
	for i, a := range resp.Acts {
		counts[i] = a.ChapterCount
	}
	ranges := assignRanges(counts, arc.StartCh, count)

	acts := make([]Act, len(resp.Acts))
	for i, a := range resp.Acts {
		acts[i] = Act{
			ID:      i + 1,
			Title:   a.Title,
			Goal:    a.Goal,
			StartCh: ranges[i].Start,
			EndCh:   ranges[i].End,
		}
	}
	arc.Outline = strings.TrimSpace(resp.Outline)
	arc.Acts = acts
	arc.Confirmed = false

	if err := SaveProgress(progressPath, state); err != nil {
		return fmt.Errorf("保存进度失败: %w", err)
	}
	logger.SuccessKey("log.arc_plan_done", ai+1, len(acts))
	return nil
}

// ConfirmArcOutlineAction marks the 卷纲 as confirmed, unlocking the 幕纲.
func ConfirmArcOutlineAction(state *Progress, progressPath string, arcID int) error {
	ai := ArcIndexByID(state, arcID)
	if ai < 0 {
		return fmt.Errorf("卷 %d 不存在", arcID)
	}
	if len(state.Arcs[ai].Acts) == 0 {
		return fmt.Errorf("第 %d 卷尚无卷纲（幕拆分），请先生成卷纲", ai+1)
	}
	state.Arcs[ai].Confirmed = true
	return SaveProgress(progressPath, state)
}

// EditArcAction edits a volume's title/goal/outline. Changing chapter_count is
// allowed only before the volume's plan is locked (no acts, not confirmed); it
// recomputes all volume ranges to stay contiguous and updates the planned
// chapter count. nil pointers keep the current value.
func EditArcAction(state *Progress, cfg *config.Config, cfgPath string, arcID int, title, goal, outline *string, chapterCount int) error {
	ai := ArcIndexByID(state, arcID)
	if ai < 0 {
		return fmt.Errorf("卷 %d 不存在", arcID)
	}
	arc := &state.Arcs[ai]
	if title != nil {
		arc.Title = strings.TrimSpace(*title)
	}
	if goal != nil {
		arc.Goal = strings.TrimSpace(*goal)
	}
	if outline != nil {
		if arc.Confirmed {
			return fmt.Errorf("第 %d 卷卷纲已确认，不能修改", ai+1)
		}
		arc.Outline = strings.TrimSpace(*outline)
	}
	if chapterCount > 0 {
		if len(arc.Acts) > 0 || arc.Confirmed {
			return fmt.Errorf("第 %d 卷已生成卷纲，不能直接修改章数（可重新生成卷纲）", ai+1)
		}
		for _, ch := range arcChapters(state, arc) {
			if ch.Status != StatusPending {
				return fmt.Errorf("第 %d 卷已有写作中的章节，不能修改章数", ai+1)
			}
		}
		counts := make([]int, len(state.Arcs))
		total := 0
		for i := range state.Arcs {
			counts[i] = state.Arcs[i].EndCh - state.Arcs[i].StartCh + 1
			total += counts[i]
		}
		counts[ai] = chapterCount
		total = total - (arc.EndCh - arc.StartCh + 1) + chapterCount
		ranges := assignRanges(counts, 1, total)
		for i := range state.Arcs {
			state.Arcs[i].StartCh = ranges[i].Start
			state.Arcs[i].EndCh = ranges[i].End
		}
		cfg.Story.ChapterCount = total
		snapshot := cfg.Story
		if state.StoryConfigSnapshot != nil {
			state.StoryConfigSnapshot = &snapshot
		}
		if err := config.SaveConfig(cfgPath, cfg); err != nil {
			return fmt.Errorf("保存配置失败: %w", err)
		}
	}
	return nil
}

// —— 幕纲 (act outline) ——

// GenerateActOutlineAction generates one act's narrative outline (幕纲).
// Requires the volume's 卷纲 to be confirmed.
func GenerateActOutlineAction(ctx context.Context, apiCfg *config.APIConfig, cfg *config.Config, state *Progress, settings *ProjectSettings, arcID, actID int, progressPath string, logger *sse.LogBroadcaster) error {
	if err := llm.ValidateConfig(apiCfg); err != nil {
		return err
	}
	ai := ArcIndexByID(state, arcID)
	if ai < 0 {
		return fmt.Errorf("卷 %d 不存在", arcID)
	}
	arc := &state.Arcs[ai]
	if !arc.Confirmed {
		return fmt.Errorf("请先确认第 %d 卷卷纲，再生成幕纲", ai+1)
	}
	ax := ActIndexByID(arc, actID)
	if ax < 0 {
		return fmt.Errorf("第 %d 卷不存在第 %d 幕", ai+1, actID)
	}
	act := &arc.Acts[ax]
	if act.Confirmed {
		return fmt.Errorf("第 %d 卷第 %d 幕幕纲已确认，如需调整请重新生成", ai+1, ax+1)
	}
	for _, ch := range actChapters(state, act) {
		if ch.Status != StatusPending {
			return fmt.Errorf("第 %d 幕范围内存在已确认/写作中的章节，无法重新生成幕纲", ax+1)
		}
	}

	lang := cfg.Language
	count := act.EndCh - act.StartCh + 1
	data := mergeOutlinePromptData(map[string]string{
		"Title":          preferUserValue(cfg.Story.Title, state.Title),
		"WritingStyle":   cfg.Story.WritingStyle,
		"WritingPOV":     cfg.Story.WritingPOV,
		"ArcIndex":       fmt.Sprintf("%d", ai+1),
		"ArcTitle":       arc.Title,
		"ArcOutline":     arc.Outline,
		"PreviousContext": buildPreviousActContext(state, ai, ax, lang),
		"ActIndex":       fmt.Sprintf("%d", ax+1),
		"ActTitle":       act.Title,
		"ActGoal":        act.Goal,
		"StartNum":       fmt.Sprintf("%d", act.StartCh),
		"EndNum":         fmt.Sprintf("%d", act.EndCh),
		"ChapterCount":   fmt.Sprintf("%d", count),
		"FutureActs":     buildFutureActsBlock(state, ai, ax, lang),
	}, cfg, settings)
	userPrompt := config.RenderPrompt(cfg.Prompts.ActOutline, data)
	userPrompt = appendIfMissingPlaceholder(cfg.Prompts.ActOutline, userPrompt, "{{.CharacterList}}", formatCharacterListForOutline(settings, cfg.Language))
	systemPrompt := i18n.SystemPromptFor(lang, "outline_editor_json")

	rawResp := llm.CallAPIWithRetryLog(ctx, apiCfg, systemPrompt, userPrompt, logger)
	if rawResp == "" {
		return fmt.Errorf("API 调用失败或被取消")
	}
	var resp struct {
		Outline string `json:"outline"`
	}
	if err := json.Unmarshal([]byte(cleanJSONResponse(rawResp)), &resp); err != nil {
		return fmt.Errorf("解析幕纲JSON失败: %w\n原始响应: %s", err, Truncate(rawResp, 500))
	}
	if strings.TrimSpace(resp.Outline) == "" {
		return fmt.Errorf("AI 未返回幕纲内容")
	}
	act.Outline = strings.TrimSpace(resp.Outline)
	act.Confirmed = false

	if err := SaveProgress(progressPath, state); err != nil {
		return fmt.Errorf("保存进度失败: %w", err)
	}
	logger.SuccessKey("log.act_outline_done", ai+1, ax+1)
	return nil
}

// ConfirmActOutlineAction marks the 幕纲 as confirmed, unlocking the 章纲.
func ConfirmActOutlineAction(state *Progress, progressPath string, arcID, actID int) error {
	ai := ArcIndexByID(state, arcID)
	if ai < 0 {
		return fmt.Errorf("卷 %d 不存在", arcID)
	}
	ax := ActIndexByID(&state.Arcs[ai], actID)
	if ax < 0 {
		return fmt.Errorf("第 %d 卷不存在第 %d 幕", ai+1, actID)
	}
	if state.Arcs[ai].Acts[ax].Outline == "" {
		return fmt.Errorf("第 %d 卷第 %d 幕尚无幕纲，请先生成幕纲", ai+1, ax+1)
	}
	state.Arcs[ai].Acts[ax].Confirmed = true
	return SaveProgress(progressPath, state)
}

// EditActAction edits an act's title/goal/outline. Changing chapter_count is
// allowed only before the act is locked (not confirmed, no chapters generated);
// it recomputes act ranges inside the volume to stay contiguous. nil pointers
// keep the current value.
func EditActAction(state *Progress, arcID, actID int, title, goal, outline *string, chapterCount int) error {
	ai := ArcIndexByID(state, arcID)
	if ai < 0 {
		return fmt.Errorf("卷 %d 不存在", arcID)
	}
	arc := &state.Arcs[ai]
	ax := ActIndexByID(arc, actID)
	if ax < 0 {
		return fmt.Errorf("第 %d 卷不存在第 %d 幕", ai+1, actID)
	}
	act := &arc.Acts[ax]
	if title != nil {
		act.Title = strings.TrimSpace(*title)
	}
	if goal != nil {
		act.Goal = strings.TrimSpace(*goal)
	}
	if outline != nil {
		if act.Confirmed {
			return fmt.Errorf("第 %d 卷第 %d 幕幕纲已确认，不能修改", ai+1, ax+1)
		}
		act.Outline = strings.TrimSpace(*outline)
	}
	if chapterCount > 0 {
		if act.Confirmed || act.ChaptersConfirmed || len(actChapters(state, act)) > 0 {
			return fmt.Errorf("第 %d 卷第 %d 幕已生成/确认，不能直接修改章数", ai+1, ax+1)
		}
		counts := make([]int, len(arc.Acts))
		for i := range arc.Acts {
			counts[i] = arc.Acts[i].EndCh - arc.Acts[i].StartCh + 1
		}
		counts[ax] = chapterCount
		ranges := assignRanges(counts, arc.StartCh, arc.EndCh-arc.StartCh+1)
		for i := range arc.Acts {
			arc.Acts[i].StartCh = ranges[i].Start
			arc.Acts[i].EndCh = ranges[i].End
		}
	}
	return nil
}

// —— 章纲 (act chapter outlines) ——

// GenerateActChapterOutlineAction generates chapter outlines for all chapters
// of one act (章纲). Requires the act's 幕纲 to be confirmed.
func GenerateActChapterOutlineAction(ctx context.Context, apiCfg *config.APIConfig, cfg *config.Config, state *Progress, settings *ProjectSettings, arcID, actID int, progressPath string, logger *sse.LogBroadcaster) error {
	if err := llm.ValidateConfig(apiCfg); err != nil {
		return err
	}
	ai := ArcIndexByID(state, arcID)
	if ai < 0 {
		return fmt.Errorf("卷 %d 不存在", arcID)
	}
	arc := &state.Arcs[ai]
	ax := ActIndexByID(arc, actID)
	if ax < 0 {
		return fmt.Errorf("第 %d 卷不存在第 %d 幕", ai+1, actID)
	}
	act := &arc.Acts[ax]
	if !act.Confirmed {
		return fmt.Errorf("请先确认第 %d 卷第 %d 幕幕纲，再生成章纲", ai+1, ax+1)
	}
	for _, ch := range actChapters(state, act) {
		if ch.Status != StatusPending {
			return fmt.Errorf("第 %d 幕范围内存在已确认/写作中的章节，无法重新生成本幕章纲", ax+1)
		}
	}

	lang := cfg.Language
	count := act.EndCh - act.StartCh + 1
	baseData := map[string]string{
		"Title":          preferUserValue(cfg.Story.Title, state.Title),
		"WritingStyle":   cfg.Story.WritingStyle,
		"WritingPOV":     cfg.Story.WritingPOV,
		"ArcIndex":       fmt.Sprintf("%d", ai+1),
		"ArcTitle":       arc.Title,
		"ArcOutline":     arc.Outline,
		"ActIndex":       fmt.Sprintf("%d", ax+1),
		"ActTitle":       act.Title,
		"ActOutline":     act.Outline,
		"PreviousContext": buildPreviousActContext(state, ai, ax, lang),
		"StartNum":       fmt.Sprintf("%d", act.StartCh),
		"EndNum":         fmt.Sprintf("%d", act.EndCh),
		"NewChapterCount": fmt.Sprintf("%d", count),
	}
	chapters, err := generateOutlineChaptersOnly(ctx, apiCfg, cfg, settings, cfg.Prompts.ActChapterOutline, baseData, logger)
	if err != nil {
		return fmt.Errorf("生成第 %d 卷第 %d 幕章纲失败: %w", ai+1, ax+1, err)
	}
	if len(chapters) == 0 {
		return fmt.Errorf("AI 未返回任何章节")
	}

	// Replace pending chapters in the act range, keep everything else ordered by Num.
	kept := state.Chapters[:0]
	for _, ch := range state.Chapters {
		if ch.Num < act.StartCh || ch.Num > act.EndCh {
			kept = append(kept, ch)
		}
	}
	for i, oc := range chapters {
		num := act.StartCh + i
		if num > act.EndCh {
			break
		}
		oc.Num = num
		kept = append(kept, chapterStateFromOutline(oc, StatusPending))
	}
	sortChaptersByNum(kept)
	state.Chapters = kept

	if err := SaveProgress(progressPath, state); err != nil {
		return fmt.Errorf("保存进度失败: %w", err)
	}
	runOutlinePostProcessChecks(ctx, apiCfg, cfg, state, settings, progressPath, logger)
	logger.SuccessKey("log.act_chapters_done", ai+1, ax+1, len(chapters))
	return nil
}

// ConfirmActChaptersAction marks the act's chapter outlines (章纲) as confirmed,
// unlocking prose generation for the act. The first confirmed act also moves
// the project into the writing phase.
func ConfirmActChaptersAction(state *Progress, progressPath string, arcID, actID int) error {
	ai := ArcIndexByID(state, arcID)
	if ai < 0 {
		return fmt.Errorf("卷 %d 不存在", arcID)
	}
	ax := ActIndexByID(&state.Arcs[ai], actID)
	if ax < 0 {
		return fmt.Errorf("第 %d 卷不存在第 %d 幕", ai+1, actID)
	}
	act := &state.Arcs[ai].Acts[ax]
	if !act.ChaptersConfirmed {
		for _, ch := range actChapters(state, act) {
			if strings.TrimSpace(ch.Outline) == "" {
				return fmt.Errorf("第 %d 幕存在无大纲的章节，请先生成章纲", ax+1)
			}
		}
		act.ChaptersConfirmed = true
		if state.Phase == "outline" {
			state.Phase = "writing"
		}
	}
	return SaveProgress(progressPath, state)
}

// —— 幕摘要 (act summary) ——

// GenerateActSummaryAction generates the summary of a completed act (幕摘要).
// It is gated by user confirmation: writing is paused before entering a new
// act until the previous act's summary is generated here. The summary then
// replaces per-chapter context for the completed act in later prompts via
// buildPreviousActContext.
func GenerateActSummaryAction(ctx context.Context, apiCfg *config.APIConfig, cfg *config.Config, state *Progress, arcID, actID int, progressPath string, logger *sse.LogBroadcaster) error {
	if err := llm.ValidateConfig(apiCfg); err != nil {
		return err
	}
	ai := ArcIndexByID(state, arcID)
	if ai < 0 {
		return fmt.Errorf("卷 %d 不存在", arcID)
	}
	ax := ActIndexByID(&state.Arcs[ai], actID)
	if ax < 0 {
		return fmt.Errorf("第 %d 卷不存在第 %d 幕", ai+1, actID)
	}
	act := &state.Arcs[ai].Acts[ax]
	if !actCompleted(state, act) {
		return fmt.Errorf("第 %d 卷第 %d 幕尚未完成（存在未确认章节），无法生成幕摘要", ai+1, ax+1)
	}
	if act.Summary != "" {
		return fmt.Errorf("第 %d 卷第 %d 幕已有幕摘要", ai+1, ax+1)
	}
	var sums strings.Builder
	for _, ch := range actChapters(state, act) {
		if ch.Summary != "" {
			sums.WriteString(fmt.Sprintf("[%d] %s\n", ch.Num, ch.Summary))
		}
	}
	if sums.Len() == 0 {
		return fmt.Errorf("第 %d 卷第 %d 幕章节尚无摘要，无法生成幕摘要", ai+1, ax+1)
	}

	logger.InfoKey("log.act_summary_generating", ai+1, ax+1)
	userPrompt := config.RenderPrompt(cfg.Prompts.ActSummary, map[string]string{
		"Title":            preferUserValue(cfg.Story.Title, state.Title),
		"ArcIndex":         fmt.Sprintf("%d", ai+1),
		"ArcTitle":         state.Arcs[ai].Title,
		"ActOutline":       act.Outline,
		"ActGoal":          act.Goal,
		"StartNum":         fmt.Sprintf("%d", act.StartCh),
		"EndNum":           fmt.Sprintf("%d", act.EndCh),
		"ChapterSummaries": sums.String(),
	})
	resp, err := llm.CallAPI(ctx, apiCfg, i18n.SystemPromptFor(cfg.Language, "author_default"), userPrompt)
	if err != nil || strings.TrimSpace(resp) == "" {
		if err == nil {
			err = fmt.Errorf("AI 未返回内容")
		}
		return fmt.Errorf("生成幕摘要失败: %w", err)
	}
	act.Summary = strings.TrimSpace(resp)
	if err := SaveProgress(progressPath, state); err != nil {
		return fmt.Errorf("保存进度失败: %w", err)
	}
	logger.SuccessKey("log.act_summary_done", ai+1, ax+1)
	return nil
}
